---
keys:
  - &admin-ndufour-2022 age1tmrr00pnj6gpc4pfp3wzvyjt66tfhudwj2kn84skt24qvwzlcsusrvrypj
  - &admin-ndufour-2023 age1n535rsu7hlyjg0p46y6du9nl0j7ldsfcmy9x9a24kxs6tuh8dgks2engp2
  - &server-mysecrets age14hltxzv2tpzutpcjr7lreet5rzcufgcx0rd3syz48v9gdkpaa45s4cfktj
  - &server-eagle age16kl8ql2sf3xf24tu0ewut2nh687jwqx5ee8h5d9d9689gqxj7p7qkfq8ag
  - &server-raccoon00 age1z49hgymr0ncyf43erzyx33r0k6tl4mrrct2vgqfm5nzplgdtpvlss90yde
  - &server-raccoon01 age1ux9fsl55rpqq2rcgwdtndtet6ukgplryuu7tps63exwf2d89333sc04ex0
  - &server-raccoon02 age18adj6q0rfpcmledgyjuwyfmjrdzrgjzvsnh5n77mht4pc7zwqplsydhjl5
  - &server-raccoon03 age1a4wtpfdgy8qm6dn5yzgr2lnntmw22v2mc067vk2u5zdv9s26rdaq5s7qv2
  - &server-raccoon04 age1xnyrzdsetaswr40qpjaq0qc97nwscz6xfjjl0v6j7kvvrntcngfq6y6tzv
  - &server-raccoon05 age1ewqzghlw2fhhjk5ek5j2grxnnyzxc2p5tczcg6ttxzgcvvxcp53qrm9hrp
  - &server-sparrow01 age1f4yjes58zf77r2lwrnf4ckl7gnmcftv6m2nwa3x7c04pp7e28djqg5sqlm
  - &server-sparrow02 age1q4eyu6q327yxxk5dkdqp3gvfec8ve0f4jnq9ugkky2qjqe22ud7s0fetr7
  - &server-sparrow03 age1h9kdsj49cnh2whfk66pjjjrh07nrpwddcv0zjt2kr527phaxvs7qvg85ka
  - &server-sparrow04 age1zwfpwda843rg86d848h6rypmrmjur9gcs4u5awzu57cvpslzqpzq95fa2r
  - &server-sparrow05 age1guve3l9udv5rzkm3u5sqte53d74fxuufzr8mhd8p0l5jt58vdpasafnsh0
  - &server-sparrow06 age1fl9qu4zlz3ndm2sqfwr44xdxv7zghtzjyytmx22srlsjsqkwz4xqa8xgj4
  - &server-opi01 age10zgavqrdukj6k6zkzmwg4klg95ll99ktmqzwyz24cn95grcqjerqcsff8w
  - &server-opi02 age1nhfx8uyrfdq99c7avexfd64qsdmlkgedlckg28zpk4wz944cuvlsg03407
  - &server-opi03 age15sz68u0tw4f7nnwuk4jz3lm230esqfktae000t62s8fwjqvl2ukslyw8g0

creation_rules:
  - path_regex: secrets/eagle/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin-ndufour-2022
        - *admin-ndufour-2023
        - *server-eagle
  - path_regex: secrets/mysecrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin-ndufour-2022
        - *admin-ndufour-2023
        - *server-mysecrets
  - path_regex: secrets/k3s-worker/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin-ndufour-2022
        - *admin-ndufour-2023
        - *server-raccoon00
        - *server-raccoon01
        - *server-raccoon02
        - *server-raccoon03
        - *server-raccoon04
        - *server-raccoon05
        - *server-sparrow01
        - *server-sparrow02
        - *server-sparrow03
        - *server-sparrow04
        - *server-sparrow05
        - *server-sparrow06
        - *server-opi01
        - *server-opi02
        - *server-opi03
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin-ndufour-2022
        - *admin-ndufour-2023

