# https://taskfile.dev

version: '3'

includes:
  nix: .taskfiles/nix/Taskfile.yaml
  sops: .taskfiles/sops/Taskfile.yaml
  sd: .taskfiles/sd/Taskfile.yaml

tasks:

  default:
    silent: true
    cmd: task -l

  lint:
    desc: Run statix lint
    cmds:
      - statix check .

  format:
    desc: Check project files
    cmds:
      - nixpkgs-fmt {{.ROOT_DIR}}