name: ci
on:
  workflow_dispatch:
  # schedule:
  #  # Those times are in UTC ...
  #  # So at 1am and 1pm
  #  - cron: '0 6,18 * * *'
  # push:
  #  branches: ["main"]
  #  paths:
  #    - '.forgejo/workflows/renovate.yaml'
  #    - 'renovate.json5'

jobs:
  renovate:
    name: Renovate
    runs-on: docker
    container:
      image: ghcr.io/renovatebot/renovate:41.21.0@sha256:33ff77e041aa811754ce5d04a2f55a2a5acf0d4b2f8b04c4ef22d80a62497965
      volumes:
        - /etc/ssl/certs/ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        env: 
          NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-bundle.crt
        with:
          show-progress: false
          repository: nemo/renovate-config
          token: ${{ secrets.RENOVATE_TOKEN }}
          path: ./renovate-config
      - name: Renovate
        uses: ./renovate-config/.forgejo/actions/common-renovate
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
          args: nemo/snowpea
          log-level: debug
