{ config, lib, pkgs, imports, modulesPath, ... }:

with lib;
{
  # NOTE
  # Some 'global' areas have defaults set in their respective modules.
  # These will be applied when the modules are loaded
  # Not the global role.
  # Not sure at this point a good way to manage globals in one place
  # without mono-repo config.

  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix") # Generated by nixos-config-generate
      ./global
    ];

  config = {

    # delete all files in /tmp during boot.
    boot.tmp.cleanOnBoot = true;

    # use DHCP to obtain an IP address
    networking.useDHCP = lib.mkDefault true;

    time.timeZone = "America/New_York";

    environment.systemPackages = with pkgs; [
      neofetch
      vim
    ];

    ## TODO see where to place those
    # Ensure ssh is up
    services.sshd.enable = true;

    # NTP time sync
    services.timesyncd.enable = lib.mkDefault true;

    security.sudo = {
      enable = true;
      wheelNeedsPassword = false;
    };
    ## END TODO
  };

}