---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

# vars:

tasks:
  update:
    desc: Update the inputs in the flake.lock file
    cmds:
      - nix flake update

  check:
    desc: Check the flake is ok
    cmds:
      - nix flake check

  list-hosts:
    desc: List the NixOS hosts in the flake
    cmds:
      - nix flake show --json 2>/dev/null|jq -r '.nixosConfigurations | keys.[]'

  deploy:
    desc: Deploy the configuration of a given host
    summary: |
      Args:
        host: machine hostname to deploy (required)
    cmds:
      - ./remote-rebuild.sh {{.host}} ndufour {{.host}}
    requires:
      vars: ["host"]

  deploy-all:
    desc: Deploy flake to all nodes
    cmds:
      - echo "This will deploy the local flake to all whitelisted hosts."
      - task: .prompt_to_continue
      - .taskfiles/nix/update-all.sh
    preconditions:
    - sh: which nix
      msg: "nix not found"
    - sh: which nixos-rebuild
      msg: "nixos-rebuild not found"

  .prompt_to_continue:
    internal: true
    prompt: Do you want to continue applying this configuration?