---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  NIX_HOSTS:
    sh: nix flake show --json 2>/dev/null|jq -r '.nixosConfigurations | keys.[]'

tasks:
  update:
    desc: Update the inputs in the flake.lock file
    cmds:
      - nix flake update

  check:
    desc: Check the flake is ok
    cmds:
      - nix flake check

  list-hosts:
    desc: List the NixOS hosts in the flake
    silent: true
    cmds:
      - echo '{{.NIX_HOSTS}}'

  deploy:
    desc: Deploy the configuration of a given host
    summary: |
      Args:
        host: machine hostname to deploy (required)
    cmds:
      - nixos-rebuild switch -j auto --use-remote-sudo --build-host {{.host}}.internal --target-host {{.host}}.internal --flake ".#{{.host}}" --fast
    requires:
      vars: ["host"]

  deploy-all:
    desc: Deploy flake to all nodes
    cmds:
      - echo "This will deploy the local flake to all whitelisted hosts."
      - task: .prompt_to_continue
      - for: { var: NIX_HOSTS, as: HOST }
        cmd: nixos-rebuild switch -j auto --use-remote-sudo --build-host {{.HOST}}.internal --target-host {{.HOST}}.internal --flake ".#{{.HOST}}" --fast
    preconditions:
    - sh: which nix
      msg: "nix not found"
    - sh: which nixos-rebuild
      msg: "nixos-rebuild not found"

  .prompt_to_continue:
    internal: true
    prompt: Do you want to continue applying this configuration?